### ISSUE TITLE
réorganisation de l’arborescence de l'appli

### ISSUE THREAD

**Issue by ploufe** [tonarii/DashboardiSpindle#1]
Hello, 
merci pour l'appli !

Après installation, je me dit qu'il serait bien de modifier légèrement l'arborescence pour avoir, à minima, un index.php dans le dossier web.
sinon, l'idéal serait aussi de garder le répertoire de base ./ pour le fichier index.php du front et de plutôt mettre un répertoire specifique (genre ./reccord) le script du ispindle.

Merci encore en tout cas

**Comment by tonarii** [comment]
Salut, 
c'est vrai que j'ai fais ça à l'arrache au départ et vu que c'était un projet perso que je ne pensais pas partager je n'ai pas modifié.
Mais j'avoue avoir un peu la flemme de me replonger la dedans ^^
