### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by ploufe** [tonarii/DashboardiSpindle#2]
Le Ispindle demande un token pour l'adresse HTTP... une idée?

**Comment by tonarii** [comment]
Salut, c'est un bug lors du changement de "type de service".
Il garde parfois afficher certaines lignes qui correspondent à d'autre service, comme le Token par exemple.
Ça vient directement du firmware "iSpindel".
Pas besoin de Token, tu peux laisser vide, ou en mettre un, ça ne changera rien. ;)
Ce n'est pas implémenté dans mon dashboard, c'est faisable, mais pas prévu pour le moment.
